{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hapi.hapiplugin",
    "module": "HapiAppMonitorPlugin",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "HapiAppMonitorPlugin-1.0.jar",
          "url": "HapiAppMonitorPlugin-1.0.jar",
          "size": 46831,
          "sha512": "6ef91c27ca11cec51b8f0c2aa39b43cef3022f982b7817ed71d7c49c8058ae9f6fdfc4915c68ca568577a48a3731d3179ab628783b2fb75b0cb15194b0328cdb",
          "sha256": "4651aef39d00f17d731954dd446b84e65cf58369ebfd312066ca54f71cb31321",
          "sha1": "0cee89ef2ac743048243819dbd701653270fe335",
          "md5": "31e0c853e13f86fc379e0a4b6f4988af"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.2"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "HapiAppMonitorPlugin-1.0.jar",
          "url": "HapiAppMonitorPlugin-1.0.jar",
          "size": 46831,
          "sha512": "6ef91c27ca11cec51b8f0c2aa39b43cef3022f982b7817ed71d7c49c8058ae9f6fdfc4915c68ca568577a48a3731d3179ab628783b2fb75b0cb15194b0328cdb",
          "sha256": "4651aef39d00f17d731954dd446b84e65cf58369ebfd312066ca54f71cb31321",
          "sha1": "0cee89ef2ac743048243819dbd701653270fe335",
          "md5": "31e0c853e13f86fc379e0a4b6f4988af"
        }
      ]
    }
  ]
}
