{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hapi.hapiplugin",
    "module": "HapiAppMonitorPlugin",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "HapiAppMonitorPlugin-1.0.jar",
          "url": "HapiAppMonitorPlugin-1.0.jar",
          "size": 46354,
          "sha512": "d704834fb5ddf9a308a2ea1fc14f1010a63b911f6c2846956c6a229d62db4bf8ec3fbe95a37b7311715909f41d6e4202a613636c13775986e51379f88cb45950",
          "sha256": "e500e9220cf779185405d10536fc32660a2655ba13acff750b40251e553d3f29",
          "sha1": "f53e04efa5568dc5a32c1c05ede0aad125619678",
          "md5": "b976890fd48d1f531672b063043cf03c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.2"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "HapiAppMonitorPlugin-1.0.jar",
          "url": "HapiAppMonitorPlugin-1.0.jar",
          "size": 46354,
          "sha512": "d704834fb5ddf9a308a2ea1fc14f1010a63b911f6c2846956c6a229d62db4bf8ec3fbe95a37b7311715909f41d6e4202a613636c13775986e51379f88cb45950",
          "sha256": "e500e9220cf779185405d10536fc32660a2655ba13acff750b40251e553d3f29",
          "sha1": "f53e04efa5568dc5a32c1c05ede0aad125619678",
          "md5": "b976890fd48d1f531672b063043cf03c"
        }
      ]
    }
  ]
}
